name: CI | Carbon lib & catalog app

on: [ push, pull_request ]

jobs:
  lib-build:
    name: Build library module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Official Gradle Wrapper Validation Action
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt

      - name: Set up Gradle cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ github.run_id }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew script
        run: chmod +x gradlew

      - name: Build lib module except catalog app
        run: ./gradlew build -x :catalog:build -x check

  lib-check:
    name: Run check tasks on library module
    runs-on: ubuntu-latest
    needs: lib-build
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt

      - name: Set up Gradle cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ github.run_id }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Check :carbon
        run: ./gradlew :carbon:check

      - name: Tests reporting
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/test-results/testReleaseUnitTest/**/*.xml'
          detailed_summary: true

  catalog-app-build:
    name: Build catalog app
    runs-on: ubuntu-latest
    needs: lib-build
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt

      - name: Set up Gradle cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ github.run_id }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Build catalog app
        run: ./gradlew :catalog:build

  delete-cache:
    name: Delete cache
    if: always()
    runs-on: ubuntu-latest
    needs: [ lib-check, catalog-app-build ]
    steps:
      - uses: actions/checkout@v2

      - name: Delete cache
        run: |
          gh extension install actions/gh-actions-cache
          set +e
          gh actions-cache delete ${{ runner.os }}-gradle-${{ github.run_id }} --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
