name: CD | Publish library to GitHub Packages
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution:

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble lib
        run: ./gradlew :carbon:assemble --scan

      - name: Publish package
        run: ./gradlew :carbon:publishMavenPublicationToGitHubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
